### ISSUE TITLE
Prompts get misaligned after resizing the window.

### ISSUE THREAD

**Issue by haccks** [bhilburn/powerlevel9k#992] opened 2018-09-16 22:20 UTC
I just noticed on resizing the window left and right prompts get misaligned as shown in the screenshot below  

<img width="834" alt="screen shot 2018-09-17 at 3 40 55 am" src="https://user-images.githubusercontent.com/6403873/45601560-aa1aa380-ba2c-11e8-9338-8d241e7c5380.png">

Is any one experiencing the same problem?
Let me know if you guys need any other informations.

**Comment by fgallardograzio** [comment] 2018-10-23 19:32
@haccks what terminal are you using? iTerm?

@bhilburn This looks like a duplicate of #881?
If so, I understand this isn't an issue with P9K, but given your comment on that issue you seem to know the details of why this is happening... could you please elaborate? So that we can look for a solution in the right direction. :smiley: 

I tried with only one prompt element, static (no changing content), text only (no icons, separators or new lines), and no right prompt. All in a newly launched terminal. This is still happening, although it's less chaotic of course.
I tried with a different oh-my-zsh theme, still happening.
I tried this resizing tmux panes instead of the whole terminal window, still happening.
However, I did every kind of terminal resize and movement I could think of for an embarrassingly long time with bash instead of zsh, and this never happened.

So, is this a zsh issue?
I see that it does re-print the prompt on every resize event, so perhaps it's an issue with zero-size control characters when deleting the old prompt to re-print the new one, maybe?
Or a race condition? Basically zsh not being fast enough to delete the existing prompt and replace it with the updated one before the next resize event causes a new delete+print cycle? So you end up with only a half-deleted old prompt.

Btw, I'm on Linux and I can just as easily reproduce this with gnome-terminal, terminator and even xterm (which doesn't show the patched font's icons).

Thanks!

**Comment by haccks** [comment] 2018-10-26 12:53
@fgallardograzio I am using iTerm2 (Build 3.2.4beta4). And seriously don't know why this is happening but one thing I know is this is making me sick!

**Comment by bhilburn** [comment] 2018-10-26 13:12
This is indeed a duplicate of #881, as @fgallardograzio points out. Unfortunately, this isn't anything that can be addressed in P9k or fonts, as this is simply how your terminal emulator is re-drawing prompts with ZSH.

I don't know the hard details of why emulators do this, but I'm sure there is a good design reason for them to have been written this way as they all seem to follow the same pattern. What you are seeing is the emulator+ZSH attempting to re-draw at different intermediate stages of your resize, rather than just doing it once at the end. Additionally, when the emulator re-draws the prompt, it seems like the size that ZSH is drawing to doesn't match the actual emulator size - which is why you see it staggered all over the screen.

To be clear, it might not be the above -- that's just me speculating based on having seen this for many years with ZSH. I'm sure other people with deeper knowledge of ZSH and/or terminal emulators would have much more to say.

**Closed by bhilburn** 2018-10-26 13:12 UTC
