### ISSUE TITLE
Strange node behavior

### ISSUE THREAD

**Issue by sevenfoxes** [bhilburn/powerlevel9k#250] opened 2016-04-21 00:07 UTC
node segment only appears to show when it's set to specific versions. This could be my machine, however, it works with an identical configuration on my other machine.

<img width="707" alt="screen shot 2016-04-20 at 7 05 54 pm" src="https://cloud.githubusercontent.com/assets/809000/14694122/f33cdf0e-072a-11e6-97a3-a81d61201c36.png">

here's my config:

```
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_RPROMPT_ON_NEWLINE=true
POWERLEVEL9K_MODE='awesome-patched'
POWERLEVEL9K_SHORTEN_DIR_LENGTH=3
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_middle"
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(root_indicator dir nvm vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(pair_info status time)
POWERLEVEL9K_NVM_BACKGROUND='28'
POWERLEVEL9K_NVM_FOREGROUND='15'
POWERLEVEL9K_TIME_FORMAT="%D{%H:%M \uE868  %d.%m}"
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="\n%{%F{249}%}\u250f"
POWERLEVEL9K_MULTILINE_SECOND_PROMPT_PREFIX="%{%F{249}%}\u2517%{%F{default}%} "

ZSH_THEME="powerlevel9k/powerlevel9k"
```

**Comment by dritter** [comment] 2016-04-21 00:24
The code for the `nvm` segment is quite small.

First, we check if `nvm current` gives us anything useful (not empty, and not "none"). After that, we try to figure out if the selected node version is not the default one. If so, we show the segment. This is what happens in your screenshot. 

```zsh
# Node version from NVM
# Only prints the segment if different than the default value
prompt_nvm() {
  [[ ! $(type nvm) =~ 'nvm is a shell function'* ]] && return
  local node_version=$(nvm current)
  [[ -z "${node_version}" ]] || [[ ${node_version} = "none" ]] && return
  local nvm_default=$(cat $NVM_DIR/alias/default)
  [[ "$node_version" =~ "$nvm_default" ]] && return

  $1_prompt_segment "$0" "$2" "green" "011" "${node_version:1}" 'NODE_ICON'
}
```

**Comment by sevenfoxes** [comment] 2016-04-21 00:26
ohhh, I see. 5.5 is set as the default on my machine, therefore, it's not showing it to me. I just installed a different version to see if that was the case and it seems accurate.

**Comment by dritter** [comment] 2016-04-25 05:31
Could you close the issue, if this solved your problem? :)

**Closed** 2016-04-25 14:02 UTC

**Comment by michaeljhopkins** [comment] 2016-05-17 21:37
No issue, posting for anybody that gets here by searching "nvm" in the issues due to the segment not showing up.

I was having this issue and I believe it was caused by the fact that nvm was already loaded before the theme did its stuff. At least, by moving all my nvm stuff to the bottom of my `~/.zshrc` then the segment was showing up right away.
