### ISSUE TITLE
Awesome Powerline Fonts dose not worked

### ISSUE THREAD

**Issue by lanffy** [bhilburn/powerlevel9k#93] opened 2015-09-13 13:51 UTC
this is my .zshrc content:
```
# Path to your oh-my-zsh installation.
# Path to your oh-my-zsh installation.
export ZSH=/Users/rlanffy/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
#ZSH_THEME="agnoster"
ZSH_THEME="powerlevel9k/powerlevel9k"
DEFAULT_USER=""
POWERLEVEL9K_MODE='awesome-patched'
#POWERLEVEL9K_MODE='flat'
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
#POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="↱"
#POWERLEVEL9K_MULTILINE_SECOND_PROMPT_PREFIX="↳ "

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"
```

I installed pro like **how to install** as your said.

when the config is **POWERLEVEL9K_MODE='awesome-patched'** and the terminal is like this:
![terminal1](http://7xjh09.com1.z0.glb.clouddn.com/terminal1.png)

when the config is **POWERLEVEL9K_MODE='flat'** and the terminal is like this:

![terminal2](http://7xjh09.com1.z0.glb.clouddn.com/terminal2.png)

**Comment by bhilburn** [comment] 2015-09-13 21:01
@lanffy - Just to confirm, if you comment out the `POWERLEVEL9K_MODE` setting, does everything render correctly? You won't be using the "Awesome Font", obviously, but does the normal config work correctly?

**Comment by lanffy** [comment] 2015-09-14 01:43
@bhilburn ,thank you for your answer.
When I close the **POWERLEVEL9K_MODE** config like this:
**#POWERLEVEL9K_MODE='flat'** and **POWERLEVEL9K_MODE='awesome-patched'** 
the terminal looks like this:
![terminal3](http://7xjh09.com1.z0.glb.clouddn.com/terminal3.png)

So, how can use terminal like this:
![googTerminal](https://cloud.githubusercontent.com/assets/1544760/7959660/67612918-09fb-11e5-9ef2-2308363c3c51.png)

**Comment by dritter** [comment] 2015-09-14 07:47
@lanffy can you close this issue, as this is a duplicate of https://github.com/gabrielelana/awesome-terminal-fonts/issues/18

**Closed** 2015-09-14 08:11 UTC

**Comment by JiaoZiLang** [comment] 2018-03-31 13:20
solve the same problem

**Comment by thanhbv2** [comment] 2018-05-01 08:45
<img width="565" alt="screen shot 1734-08-23 at 15 44 39" src="https://user-images.githubusercontent.com/33213257/39467139-a2f92c7c-4d56-11e8-8f69-2bad7f25fc30.png">

**Comment by thanhbv2** [comment] 2018-05-01 08:45
can we help me solve it

**Comment by bhilburn** [comment] 2018-05-01 12:52
@JiaoZiLang @thanhbv2 - It looks like your fonts are not installed or configured correctly. Please follow the [Installation Instructions](https://github.com/bhilburn/powerlevel9k/wiki/Install-Instructions#step-2-install-a-powerline-font) and then configure your terminal to use your installed font. If you are still having issues, open a new bug and include information about how you've installed P9k and the fonts and how you have configured things. Thanks!
