### ISSUE TITLE
Problem: Gnome-Terminal displays segment color after newline if using two newline - segments

### ISSUE THREAD

**Issue by bytekeks** [bhilburn/powerlevel9k#957] opened 2018-08-17 06:13 UTC
Hi,

please see following screenshot:

![screenshotpowerlevel9ksegmentcolorissue](https://user-images.githubusercontent.com/4034031/44250195-b45e3d80-a1f3-11e8-9857-3ebe0bc254f9.png)

As you can see, the color of the status segment is displayed after the newline.

I'm using ohmyzsh and my .zshrc config is as follows:
```
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir status newline vcs newline)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(time)
POWERLEVEL9K_DISABLE_RPROMPT=true
POWERLEVEL9K_CUSTOM_PROMPTICON="echo \>"

# HIDE current user in prompt
DEFAULT_USER=`whoami`

# load solarized dir colors
eval `dircolors ~/.dircolors/dircolors.ansi-dark`
```

It doesn't matter what segments I use. If using two `newline` statements, this error occurs.

Does anybody know a solution to this or is it just not recommended to use two newline statements?

Thanks ;)

**Comment by ChrisSeattle** [comment] 2018-10-25 02:10
I have the exact same problem. I'm on Ubuntu 18.04, using oh-my-zsh. All other configurations seem to work as expected, but this little annoyance keeps showing up.

**Comment by bhilburn** [comment] 2018-10-26 18:33
Hm, interesting. And weird that it's actually showing the segment BG color of the segment on the top line, not of the segment on the second line.

@bytekeks @ChrisSeattle - Are you guys using a release or the `master` branch, by chance? Can you give the `next` branch a shot and let us know if the behavior is the same?

**Comment by bhilburn** [comment] 2018-11-02 12:48
@bytekeks - Whoa, really? The latest `master` fixed it for you?

@ChrisSeattle - Can you test & confirm as well?

**Comment by bytekeks** [comment] 2018-11-02 13:11
@bhilburn indeed. The issue is gone :)

It seems, that using no seperator icons lead to this problem in the old version.

```
POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=""
POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=""
```
In the current master, leaving SEPERATOR empty will just be ignored and the default is used, right?

**Comment by bhilburn** [comment] 2018-11-05 15:19
Great! I'm so happy to hear the issue is resolved in the `next` branch. That means a fix will be included in the next release.

@bytekeks - If you don't define the separator at all, then the default is used. If you define it to be empty, then it will be empty -- which was probably the cause, per your suspicion =)

I'm closing this issue since it's resolved in `next`. Please re-open if you are still experiencing this!

**Closed by bhilburn** 2018-11-05 15:19 UTC
Labels: bug
