### ISSUE TITLE
Strange behaviour with truncate_to_unique

### ISSUE THREAD

**Issue by G4Zz0L1** [bhilburn/powerlevel9k#907] opened 2018-07-13 14:41 UTC
I've a strange behaviour with the option `POWERLEVEL9K_SHORTEN_STRATEGY="truncate_to_unique"`

If I set it that way the prompt returns
`prompt_dir:66: no matches found: //.*/`
if the folder is a hidden one, or 
`prompt_dir:66: no matches found: //D*/`
if the folder starts with D

But it's pretty random, in some folder it returns that and in other works normally

If i remove that row from the .zshrc it works flawlessly in every folder

gnome-terminal 3.28.1-1ubuntu1mint2
zsh 5.4.2 (x86_64-ubuntu-linux-gnu)
oh-my-zsh and p9k cloned from git, latest

**Comment by nvonbulow** [comment] 2018-07-17 01:58
I am having this same issue

**Comment by bhilburn** [comment] 2018-07-18 13:34
@G4Zz0L1 - Thanks so much for the bug report, and thanks for confirming, @nvonbulow!

@onaforeignshore has already put together a fix. Can you check out #915, give that PR a shot, and let us know if it resolves your issue?

**Comment by diraol** [comment] 2018-07-18 14:56
It kind of works for me too, but with a strange behavior regarding the beginning of the path printed on the screen:
![2018-07-18-115453_313x69_scrot](https://user-images.githubusercontent.com/192702/42889725-7cb8c334-8a81-11e8-8739-498033ae331c.png)

That `~h/d/` seems wrong to me, it should be `~/` or `/h/d/`

**Comment by onaforeignshore** [comment] 2018-07-18 15:01
What is the content of your `$HOME` variable?

**Comment by nvonbulow** [comment] 2018-07-18 15:06
I'm having the same weird path beginning as @diraol with the unwanted `~h`. My `$HOME` is set to `/home/nick`

**Comment by onaforeignshore** [comment] 2018-07-18 15:29
I have updated the fix. Can you please pull it again and see if the issue persists?

**Comment by nvonbulow** [comment] 2018-07-18 15:35
The issue is still there. It doesn't look like anything changed

**Comment by diraol** [comment] 2018-07-18 15:51
It is better now for me.

**Comment by nvonbulow** [comment] 2018-07-18 15:56
With the addition of the code simplification commit, everything works for me now.

**Comment by onaforeignshore** [comment] 2018-07-18 15:57
@nvonbulow That's good news.

**Comment by bhilburn** [comment] 2018-07-19 12:47
Thanks so much, @nvonbulow and @diraol, for testing the fix in #915! And thanks for filing the initial bug report, @G4Zz0L1! Great work, everyone.

The fix #915 has been merged into master `=)`

**Closed by bhilburn** 2018-07-19 12:47 UTC
