### ISSUE TITLE
Commands not completing

### ISSUE THREAD

**Issue by rwinand** [bhilburn/powerlevel9k#462] opened 2017-03-31 14:20 UTC
I am running zsh on a remote server (Ubuntu 14.04) that I access through ssh. I am using a default installation without any special configurations yet. Everything works fine in the directories that I own but in some directories owned by others (but that I have read access to) I get some weird behavior.

If I try to change to one of those directories (e.g. /home/other_user) the command does not seem to execute and the cursor just goes to a new line without showing the prompt. Hitting CTRL-C will give me the old prompt again (e.g. /home/me) but the directory did actually change to the requested one in the background. So while the prompt displays the original directory, any command executed will be done in the other directory.

Running a simple command like `ll` does almost the same thing: you get the output of the command but no prompt, the only way to get the prompt back is by hitting CTRL-C.

Do you have any idea what could be causing this behavior?

**Comment by dritter** [comment] 2017-03-31 20:10
Hi @rwinand !
Thanks for the report. Interesting. I quickly created a folder and set permissions to executable only (in all variations: owner, group, others), but was not able to reproduce that issue. Could you elaborate more on what are the exact rights that the other folder has? Do you use ACL?

And do you use any ZSH framework? Does it happen without / another framework?

**Comment by onaforeignshore** [comment] 2017-04-01 08:03
What versions of zsh and ssh are you using?

**Comment by bhilburn** [comment] 2017-04-04 00:44
Welcome, @rwinand! Just a ping on @dritter's and @onaforeignshore's questions :)

**Comment by rwinand** [comment] 2017-04-04 06:12
I apologize for the late reply, I went for on a long weekend after posting this and probably should have posted this when I got back ... 

To answer your questions: I am using Oh My Zsh but it also happens when I try it with a vanilla zsh installation. The version of zsh I am using is 5.0.2 (default one in Ubuntu 14.04) and I am connecting to an OpenSSH server version 6.6.1p1.

We are not using ACL. I have also found now that the folders that I have troubles with are all children from one user's /home folder which is set to permission 755 and owned by other_user:other_group. Other folders owned by that same user and group but which are not located under /home/other_user work fine (for the ones I tested up to now at least). I tried changing the permissions but that doesn't solve the problem. Also, home folders for completely different users (and groups) don't have this issue.

**Comment by rwinand** [comment] 2017-04-04 06:54
I think I may have found the cause. The user home directory that I have the issues with is a directory with a git repo but one with a subtree. So there is data from two git repos from different servers in that one directory. This is the only difference that I could find between all the directories that I checked.

**Comment by bhilburn** [comment] 2017-04-12 20:43
@rwinand - Thanks for getting back to us!

Yeah, the subtree thing really ought to work, as ZSH's `VCS_INFO` module is supposed to be able to deal with those. If no one can recreate this, including you, we might have to close this one :-/

What about the permissions on the `.git/` folder and `.gitmodules` in the directory?

**Comment by bhilburn** [comment] 2017-04-18 22:46
Just a ping on this! :)

**Comment by bhilburn** [comment] 2017-04-20 15:52
Going to close this one due to inactivity. Feel free to re-open, @rwinand! =)

**Closed by bhilburn** 2017-04-20 15:52 UTC
Labels: question, unclear
