### ISSUE TITLE
Adapt battery segment from neofetch

### ISSUE THREAD

**Issue by dritter** [bhilburn/powerlevel9k#365] opened 2016-12-19 21:07 UTC
[Neofetch](https://github.com/dylanaraps/neofetch) is a pretty awesome project. They have found an easier and (maybe) more reliable way for the [battery segment](https://github.com/dylanaraps/neofetch/blob/master/neofetch#L1579-L1657). Maybe we could adapt some of their ideas to our battery segment.

Additionally, they have some other cool stuff, like external IP, played song, etc.

**Comment by rjorgenson** [comment] 2016-12-19 22:29
I like this a lot, much cleaner than using ioreg. I did a quick rewrite and was doing some testing and noticed that it seems to do be not as exact as ioreg.

<img width="820" alt="screen shot 2016-12-19 at 3 18 21 pm" src="https://cloud.githubusercontent.com/assets/44096/21331233/876e9ff4-c5fe-11e6-89d1-c7c389be198e.png">

I'm not sure how important this is from an actual use case scenario, personally it doesn't bother me a lot assuming this is the extent of it. I'd have to do more testing on it. I'll submit a PR with my changes so others can help test edge cases and speed stuff. In my limited testing it seems to be a bit faster, but I haven't confirmed that with any tests or anything.

**Comment by rjorgenson** [comment] 2016-12-19 22:36
PR #366

**Comment by bhilburn** [comment] 2016-12-30 19:17
Merged!

**Closed by bhilburn** 2016-12-30 19:17 UTC
