### ISSUE TITLE
Latin characters not showing, numbers instead

### ISSUE THREAD

**Issue by jppmarujo** [bhilburn/powerlevel9k#734] opened 2018-01-31 20:04 UTC
Hello,
First of all, i have to state this is my first time using zsh and powerlevel9k - a whole new wonderful world. 
I set up everything OK, downloaded powerline patched fonts, and was trying to use tunnckoCore configuration:

`POWERLEVEL9K_MODE='awesome-patched'
POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status nvm node_version)

POWERLEVEL9K_OS_ICON_BACKGROUND="white"
POWERLEVEL9K_OS_ICON_FOREGROUND="blue"
POWERLEVEL9K_DIR_HOME_FOREGROUND="white"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="white"
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="white"`

The thing is: i can see icons and everything, but if i do an 'ls' on the terminal, since my Gnome is in Portuguese (Portugal), we have characters like «ú» «ê» or «à» that don't show up.
They're replaced with numbers.

I've tried searching for other powerline patched fonts, and used them, but none of them was able to correctly show the folders name. 

Please see the screenshot:

![screenshot_symbols](https://user-images.githubusercontent.com/32954931/35644814-f250bf28-06c1-11e8-832b-ebe195716efa.png)

Can you help me fixing this? 
Thank you in advance, and congratulations for this amazing project!

**Comment by bhilburn** [comment] 2018-02-02 16:32
Thanks for the kind words! I'm glad you like it =)

Hm, I've never seen an issue like this. Out of curiosity, if you use a different ZSH theme, do you see the same issues? Trying to nail down if this is a P9k issue or a terminal+font issue. It seems to me that it's the latter, but I want to be sure.

**Comment by gersongams** [comment] 2018-02-08 21:36
I'm having the same issue with latin characters for example in spanish:

![captura de pantalla de 2018-02-08 16-35-25](https://user-images.githubusercontent.com/12853243/35999536-291e8daa-0cee-11e8-8c82-04206ffe11f0.png)

**Comment by shortlisted** [comment] 2018-02-22 14:26
I have the same problem with swedish characters when using powerlevel9k. The issue vanishes if I swap theme. I seem to get the same problem regardless of which type of font I use (currently using Awesome powerline, but I've tried to other options as well)

With powerline I get
![powerline](https://user-images.githubusercontent.com/14911221/36543608-84378eb6-17e4-11e8-9fc0-7121793ed6c5.png)

swapping to pygmalion I get the following
![pygmalion](https://user-images.githubusercontent.com/14911221/36543543-5b0da7aa-17e4-11e8-9d76-6a6ad6481211.png)

Using antergos/i3/termite

**Comment by shortlisted** [comment] 2018-02-23 11:30
I found the issue. The problem is in the file `functions/icons.zsh`. All the cases contain the line `LC_CTYPE="en_US.UTF-8"`, overriding the correct environment variable (for me `"sv_SE.UTF-8"`)

If that check is actually needed, I made a change to the code where it only sets the LC_CTYPE if the variable is unset, I can do a pull request if you want to add it.

If someone just wants a quick fix for this without having to think about the powerline code, `export LC_CTYPE="sv_SE.UTF-8"` in your .zshrc will remove the issue.
![fixed](https://user-images.githubusercontent.com/14911221/36592232-280ae528-1895-11e8-949b-dc3834f2bc16.png)

**Comment by jppmarujo** [comment] 2018-02-26 09:24
Thank you, shortlisted.

I can now use powerlevel9k on my native language, without any problem.

And you even saved the dev some time. A round of applause!

2018-02-23 11:30 GMT+00:00 shortlisted <notifications@github.com>:

**Comment by bhilburn** [comment] 2018-03-26 02:37
@shortlisted - This is excellent! Would you mind putting together a PR and submitting it against `master`? It would be great to get this upstreamed for everyone's benefit `=)`

**Comment by jppmarujo** [comment] 2018-03-26 07:21
@bhilburn and @shortlisted , just remember that this solution is specific for Swedish, so a pull request will only cover the issue for users from Sweden. I changed it to my country language when applying the changes, as i don't know if `export LC_CTYPE="sv_SE.UTF-8"` will cover all other characters, like the latin ones.

**Comment by bhilburn** [comment] 2018-03-26 18:22
@jppmarujo - Ah, I misunderstood, and after re-reading this, you're right, there's little we can do to detect exactly how it is wrong.

For now, the best thing might be adding a section to the Troubleshooting Wiki about broken characters, here: https://github.com/bhilburn/powerlevel9k/wiki/Troubleshooting

Are you up for that?

**Comment by dritter** [comment] 2018-03-26 23:50
Despite the fact that we use local variables in `functions/icons.zsh` (`local LC_ALL="" LC_CTYPE="en_US.UTF-8"`), that seems not to work with switch statements, but with functions.

Compare my little test script:
```zsh
#!/usr/bin/env zsh

MY_VAR=TEST
echo "before ${MY_VAR}"

MY_MODE='flat'
case $MY_MODE in
  'flat'|'awesome-patched')
    local MY_VAR=gotcha
    echo "inside ${MY_VAR}"
    ;;
esac

echo "after ${MY_VAR}"
```
Output:
```
before TEST
inside gotcha
after gotcha
```
But if I change the script to:
```zsh
#!/usr/bin/env zsh

MY_VAR=TEST
echo "before ${MY_VAR}"

my_method(){
  local MY_VAR=gotcha
  echo "inside ${MY_VAR}"
}

my_method

echo "after ${MY_VAR}"
```
It works!

Output:
```
before TEST
inside gotcha
after TEST
```
So, the value of `${MY_VAR}` does not get overwritten by that. All we have to do is to wrap the icon definitions in a function to scope them properly.

I just wonder, why this does not happen on my system..

**Comment by dritter** [comment] 2018-03-27 20:17
@jppmarujo and @shortlisted could you try out my branch [dritter/fix_leaking_lcctype](https://github.com/dritter/powerlevel9k/tree/fix_leaking_lcctype) ?
In this branch I created a function around the icon definitions to create scope and prevent leakage of `LC_CTYPE`.
I can't reproduce this issue on my machine, but I am sure that this will fix the issue. If you can confirm, I'll create a PR.

**Comment by dritter** [comment] 2018-03-30 17:11
The origins of this are in #56 and in https://github.com/robbyrussell/oh-my-zsh/pull/4091

**Comment by bhilburn** [comment] 2018-10-08 21:23
Closing this one due to inactivity and a general inability on our part of fixing this due to the issues linked by @dritter in OMZ. If anyone has something further to add to this discussion, feel free to re-open!

**Closed by bhilburn** 2018-10-08 21:23 UTC
Labels: Fonts, question
