### ISSUE TITLE
Wrong cut off in Konsole

### ISSUE THREAD

**Issue by mr-ubik** [bhilburn/powerlevel9k#971] opened 2018-08-27 03:39 UTC
![Nope](https://user-images.githubusercontent.com/16547060/44639135-9abeb200-a9ba-11e8-8fcc-bd9e8cca218a.png)
Terminal Emulator: Konsole
Framework: Oh-My-Zsh
Powelevel9k: cloned from master (571a859)
POWERLEVEL9K_MODE='nerdfont-complete'
Font: Hack Nerd Font (installed via the AUR packages)

It appears that #854 is not working for me.

**Comment by mr-ubik** [comment] 2018-08-27 14:55
UPDATE: after setting LANG=n_US.UTF-8 in locale.conf to fix #639  this is the prompt that I am getting

![meh2](https://user-images.githubusercontent.com/16547060/44666783-6e864e00-aa19-11e8-85eb-3e070ebc6491.png)

If I use the Nerd Font Monoglyph variant, the output is correct, but the icons are smaller and harder to read. 

I am beginning to suspect that it's all due to the and not powerlevel9k, but I will wait for someone more knowledgeable to drop by.

![meh3](https://user-images.githubusercontent.com/16547060/44666947-d3da3f00-aa19-11e8-8776-978f328428f8.png)

**Comment by NielsonJ** [comment] 2018-08-28 12:30
I have this same issue but online since Konsole 18.08.0 dropped on me.

**Comment by harsh8398** [comment] 2018-08-30 16:35
Yes I am having the same issue currently. It was working fine when I installed it. Probably its because of the new konsole update.

**Comment by bhilburn** [comment] 2018-10-09 13:06
Okay, it sounds like this is indeed a bug in konsole. It would be good if someone (ideally a konsole user) filed a bug on Konsole's bug tracker so they are aware and hopefully push a fix in a future update.

@mr-ubik @NielsonJ @harsh8398 @AbdelrahmanGIT - Thanks so much for commenting and participating, here, and thanks @mr-ubik for opening this issue to begin with! I'm going to close this out for now since it's an external bug, but if there are any updates please share them here, or if you believe there is an issue in P9k we can resolve please re-open!

**Closed by bhilburn** 2018-10-09 13:06 UTC
Labels: external-bug

**Comment by beojan** [comment] 2018-10-24 09:17
I think the problem is adding whitespace was a workaround, not a fix.
The bug is here: https://bugs.kde.org/show_bug.cgi?id=390650
As you can see, it's a NOTABUG because the double-width characters in question are in the PUA.

**Comment by braydie** [comment] 2018-10-24 13:07
So presumably that means that the work around we had before relied on a bug in konsole..? Where _should_ the fix to make this work sit?

**Comment by beojan** [comment] 2018-10-24 13:13
Either we can figure out why xfce terminal (for instance) displays things correctly, and persuade Konsole to do the same (though it might turn out that there's a bug in XFCE terminal), or awesome-terminal-fonts can move the glyphs into the Han section of Unicode (which would break things for anyone who actually wanted to use CJK characters).

**Comment by beojan** [comment] 2018-10-24 13:16
Or Option 3, the double width characters can be implemented using two codepoints and a ligature (since ligatures *do* work in Konsole).

**Comment by VladimirMikulic** [comment] 2019-01-16 18:52
SOLUTION: I installed Tilix terminal and icons are displayed properly. Personally I am glad that I discovered Tilix, it is even better than Konsole! Maybe some of you already knew for Tilix, but I wanted to share my solution. Hopefully it will help someone. Anyways, thanks @dritter for your response :)

**Comment by beojan** [comment] 2019-04-23 11:32
The Konsole bug is [fixed](https://bugs.kde.org/show_bug.cgi?id=397669), but powerlevel9k needs to be changed to ensure there are no ANSI escape codes between the character and the space (so the escape codes need to go after the space.

**Comment by VladimirMikulic** [comment] 2019-04-23 11:44
Yeah, I noticed that change a few days ago. Konsole works fine now, good job.

**Comment by beojan** [comment] 2019-04-23 11:48
Actually, I'm still seeing an issue with the swap use segment.

**Comment by VladimirMikulic** [comment] 2019-04-23 12:02
Provide a screenshot.

**Comment by beojan** [comment] 2019-04-23 12:26
![image](https://user-images.githubusercontent.com/3727925/56580813-6e037e80-65cb-11e9-9ee3-e6c0454b7c44.png)

**Comment by VladimirMikulic** [comment] 2019-04-23 13:17
Now, I have the same issue as you. I've just upgraded from Kubuntu 18.10 to 19.04 and now Konsole doesn't work anymore.
![Konsole Screenshot]("https://cdn1.imggmi.com/uploads/2019/4/23/3406ac2a983c7f47ce509192fcf93675-full.png")

**Comment by beojan** [comment] 2019-04-23 13:20
That's because Kubuntu 19.04 comes with Konsole 18.12. Konsole 19.04 largely fixed the problems, except with the swap segment.

**Comment by VladimirMikulic** [comment] 2019-04-23 13:24
Then, I guess you'll have to wait for the next update to fix the problem with the swap segment :joy:

**Comment by dritter** [comment] 2019-04-23 16:31
@beojan Good to hear that the bug is fixed in Konsole. Not sure though, if we should add a whitespace after every icon by default. That would fix this out of the box for Konsole users, but display a big gap for other Terminal Emulators.
But it is possible right now to add a whitespace to every icon via configuration. E.g. for the Swap segments icon, just set `P9K_SWAP_ICON=$'\uF464 '` in your `~/.zshrc`, if you use P9Ks `next` branch, and NerdFonts.

**Comment by beojan** [comment] 2019-04-23 16:34
IIRC, there's already some logic (either in P9K or oh my zsh) that does
precisely that, but only on Konsole. That's why things worked before 18.04.
Evidently, this is missing for the swap segment.

**Comment by beojan** [comment] 2019-04-27 09:03
@dritter I "fixed" this by adding a space after each variable in line 123 of `function/icons.zsh`.

This would need to be in a conditional if the fix is to be distributed (maybe a P9K_SPACE_AFTER_ICONS option?)

**Comment by beojan** [comment] 2019-04-27 10:50
@dritter In fact, it turns out that with commit ad93217, the swap segment works fine. At some point since then, a change was introduced which allows escape code between the icon and the space.

**Comment by beojan** [comment] 2019-04-27 10:56
And solved. It's 4300902 that causes the problem.

**Comment by Afzal7** [comment] 2019-05-15 18:29
Did a clean install of kubuntu 19.04 and installed oh-my-zsh and powerlevel9k with nerd fonts. But its not working right :(

![terminal](https://user-images.githubusercontent.com/19857047/57799657-2953a900-776d-11e9-9215-ba167ca8b938.png)

**Comment by RaitaroH** [comment] 2019-05-19 08:32
@Afzal7 I use the MONO variant of the awesome fonts. Go to EDIT > Appeaance > Choose font > Enable Show all fonts > Choose the mono variant of what you want. Now it will work.

![image](https://user-images.githubusercontent.com/19552720/57979639-43b9ab00-7a29-11e9-95c4-9ae21a7e06bc.png)

BUT I also have this weird thing where, IF konsole is started from zsh with oh-my-zsh and powerlevel9k installed the font is not rendered properly. IF started from bash inside zsh then is fine.  Seems like #1258

**Comment by Afzal7** [comment] 2019-05-19 11:43
@RaitaroH Thanks for the reply. Did what you said. It worked but i have to say it does not look perfect. But it will work. Thanks.
![Screenshot_20190519_170839](https://user-images.githubusercontent.com/19857047/57981733-50ee8e00-7a59-11e9-9911-91fc80783cb4.png)
