### ISSUE TITLE
Showing prompt is very slow

### ISSUE THREAD

**Issue by tweety3d** [bhilburn/powerlevel9k#374] opened 2017-01-10 11:32 UTC
Hi,
I noticed that showing prompt is very slow, takes 0,5 to 1 second, meaning that after each command there is almost one second gap.
The easiest way to see it is press ENTER and hold, you'll see prompts not appearing immediately and them appearing one at a time.
Can't imagine what takes so much time there...
It's very sad, because this theme looks very nice and has nice features.
I'm using Prezto version.

**Comment by Tritlo** [comment] 2017-01-10 11:34
Is your home directory tracked in Git? If so, the cause is very probably the VCS segment slowing things down. You can try turning that off, and see if it improves the performance. 

We are currently working on an async implementation, and it should be ready soon.

**Comment by tweety3d** [comment] 2017-01-10 11:35
It's not, it runs that slow in my untracked home dir.
In any git dir it runs even slower.

**Comment by Tritlo** [comment] 2017-01-10 11:38
What segments are you using?

**Comment by tweety3d** [comment] 2017-01-10 12:33
Having only context dir and time is working fine 95% of times (once a while it doesn't finish empty command before it gets next ENTER), but it's still fine.
Adding vsc just kills it.

**Comment by dritter** [comment] 2017-01-10 17:49
This may have various causes:

1. Big repository 
Obviously, on big repositories, git cannot be super fast.

2. Many untracked files
This is a flaw in git. If you have a lot of untracked files it gets slow, because git computes (compares them against .gitignore) a list of all these files and gives us the whole list..

3. Old git version 
The git guys have done a lot of performance tweaking. So, you should upgrade your git, if you use an old version. This is for instance the case if you use a standard OSX. The shipped version of git is quite old. In that case you should consider installing git with a package manager (like [homebrew](http://brew.sh).

4. Slow HDD
At last, it boils down to raw I/O performance. The VCS segment does a lot of filesystem lookups. As @Tritlo said, we are working on rendering the segments asynchronously. You can see if that brings remedy. The PR is #344 

I hope that at least one of that helps.

**Comment by tweety3d** [comment] 2017-01-11 08:14
But, as I mentioned earlier, it happens when not in git repository. Just in my home folder or any folder for that matter.
And I have SSD so hard to make it faster :)

**Comment by dritter** [comment] 2017-01-12 11:50
Okay. Could you post the output of `git --version` anyway?

And is the prompt more usable in another directory that is not within your home folder (like `/tmp`)?

And how fast is it if you disable the `vcs` segment?

**Comment by tweety3d** [comment] 2017-01-12 12:58
git version 2.11.0.390.gc69c2f50cf-goog

With vcs segment, my "hold enter test" in tmp:
 ```
/tmp                                                                                                                                      13:55 
                                                                                                                                                    

 /tmp                                                                                                                                      13:55 
                                                                                                                                                    

 /tmp                                                                                                                                      13:55 
                                                                                                                                                    
 /tmp                                                                                                                                      13:55 
 /tmp                                                                                                                                      13:55 
```
meaning it gets 2-3 'enter' keys before it renders prompt.

And in git repo:
 ```
~/repos/code1   basee | merge                                                                                                       13:56 
                                                                                                                                                    







 ~/repos/code1   basee | merge                                                                                                       13:56 
                                                                                                                                                    






 ~/repos/code1   basee | merge                                                                                                       13:56 
```
meaning, it gets 8 'enter' keys before it renders prompt.

Removing vcs segment makes it much faster, 95% of time rendering prompt on time.

Unfortunately, after checking out zsh-async-integration zsh won't start at all. No errors, just hangs I guess.

**Comment by dritter** [comment] 2017-01-12 16:08
Well. I don't think we can do anything about that (except for more profiling, and disabling hooks one by one). The `vcs` segment is quite heavyweight. That is one of the main reasons why we started implementing the segments asynchronously.

Btw. the `zsh-async-integration` branch is not the one I meant. The right one is not a branch, but a fork on my side (you can find the code here: https://github.com/dritter/powerlevel9k/tree/async_all_the_segments). Try that one, and let us know if that is fast enough.

**Comment by jshort** [comment] 2017-01-18 18:31
I got powerlevel9k setup yesterday and in the early stages it seemed just as fast to render as, say agnoster, but as I started configuring it, it became very slow.

After some iteration this morning, I found that the battery segment is the culprit fwiw.  Is there anything that can be done to speed that segment up?  Maybe only checking level modulo 5 minutes or 5 prompts or something?

**Comment by rjorgenson** [comment] 2017-01-18 18:42
@jshort hmmm, what operating system are you on? I just tested my prompt with and without the battery segment and couldn't notice any difference on OS X. The battery segment doesn't really do anything system intensive, just read some values and simple math. I'm on next branch right now which has a new method of getting battery information on OS X but in my tests the new method wasn't any faster than the old version, just a bit cleaner.

**Comment by jshort** [comment] 2017-01-18 20:10
OSX El Capitan.  Link to the git commit you are on please?

**Comment by rjorgenson** [comment] 2017-01-18 20:28
@jshort yes those are the changes that I'm using, but I'm actually on commit c5909e7 which has a few other non-related changes. But I didn't notice any speed difference between pre 16283fc and post 16283fc

**Comment by jshort** [comment] 2017-01-18 21:40
On the HEAD of branch `next`, the battery indicator (and my prompt in general) renders very fast.

@tweety3d Can you try the `next` branch to see if that speeds things up for you?

**Comment by jshort** [comment] 2017-01-18 22:53
@rjorgenson 

See https://github.com/bhilburn/powerlevel9k/pull/376

**Comment by bhilburn** [comment] 2017-01-21 20:36
@tweety3d - I just merged @jshort's fix in #376. Can you check out the HEAD of `next` and let us know if it helps?

**Comment by tweety3d** [comment] 2017-01-23 08:57
Hi,
I've checkout out newest next and still the same lag...

**Comment by bhilburn** [comment] 2017-01-23 15:37
Okay, so the battery segment changes fixed @jshort's problems, but not @tweety3d's. It sounds like @tweety3d's issues are indeed `vcs` related, but it's very strange that it's happening even outside of a `git` directory. `git-2.11` is the latest version, so this isn't an "ancient version" problem, either.

@dritter's async branch would be the ideal solution. @tweety3d it sounds like you tried the `zsh-async-integration` *branch*, but what we actually want you to try is this fork:
https://github.com/dritter/powerlevel9k/tree/async_all_the_segments

Go into your powerlevel9k.git directory, and:

```zsh
git remote add dritter https://github.com/dritter/powerlevel9k.git
git remote update -p
git checkout -b async -t dritter/async_all_the_segments
```

Then restart your terminal and let us know how it goes!

**Comment by DavidAwad** [comment] 2017-01-23 18:52
Trying the fork for myself after reading this it is a little faster, I should also add that if you have a lot of extra directories in your $PATH variable it can slow down loading the prompt. 

Take a look in your bashrc and zshrc and see if anything there is adding a lot to the $PATH variable. 

You can also check it with `echo $PATH`

**Comment by tweety3d** [comment] 2017-01-24 09:34
Wow!
So much better!
In /tmp it's successful 95% of time, while in git directory it doesn't display git part in 40% of time, but still new prompt appears immediately, which is great.
Thanks, I'm hoping you can merge that branch soon :)

The only thing, sometimes when I hold ENTER in git directory some errors appear:
serialize_segment:84: no such file or directory: /tmp/p9k/p9k_14971_left_003_prompt_vcs.sh

**Comment by tweety3d** [comment] 2017-01-24 09:49
To add to this, when in git repository it takes about one second for the git segment to appear, but the prompt is ready and I'm able to type during this second.

But I wonder, what takes one second there? Executing 'git branch' or 'git log' takes no-time, so even parsing that text and displaying segment should also take up to 1 ms I would say...

**Comment by bhilburn** [comment] 2017-02-14 01:54
@DavidAwad - Great advice!

@tweety3d - So glad you like @dritter's work on the async stuff! He is putting a lot of time & effort into it, and we are really excited to get it merged once it's ready =)

**Closed** 2017-02-14 01:55 UTC
Labels: bug, question

**Comment by ijoseph** [comment] 2018-08-30 17:28
>  I should also add that if you have a lot of extra directories in your $PATH variable it can slow down loading the prompt.

@davidawad , what counts as "a lot"? I have 13. 

Also, on the practical side [`typeset -aU path` to the end of `.zshrc` gets rid of duplicate `$PATH` entries](https://til.hashrocket.com/posts/7evpdebn7g-remove-duplicates-in-zsh-path).

**Comment by ijoseph** [comment] 2018-08-30 17:35
Unfortunately, #344 `dritter/async_all_the_segments` fork did not solve my slow rendering issues.

**Comment by dritter** [comment] 2018-11-12 23:00
@ijoseph @LightningsFury #344 turned out to be a dead end - unfortunately. Our current development branch is `next`, where we did some great speed improvements. Could you try out this branch, and tell us your experience?

**Comment by ijoseph** [comment] 2018-11-12 23:16
@dritter Will do within the week, and check back. Thanks for checking in.

**Comment by ijoseph** [comment] 2018-11-12 23:50
Quite an improvement. From about 0.5 seconds to render the prompt each time, down to about 0.1 seconds (on non-`git` directories). Happily, crossed the threshold of usability from unusuable to usable.

**Comment by dritter** [comment] 2018-11-13 00:42
Awesome @ijoseph

**Comment by ijoseph** [comment] 2018-11-13 21:11
@dritter  I've actually putting in quite a bit of effort to figure out why my prompt renders so slowly. Confoundingly, on my work MacBook, it (used to be) significantly slower than my home MacBook (0.5 seconds versus 0.1 seconds). 

After changing to the `next` branch, [long story](https://xebia.com/blog/profiling-zsh-shell-scripts/) short, is that the command (function?) `+vi-git-untracked` seems to be taking the Lion's Share of the rendering time.

**Comment by dritter** [comment] 2018-11-13 21:40
Is this repo a big one? In #1046 I've written down some scenarios and some simple measurements. Could you quantify your repo on that terms?

**Comment by ijoseph** [comment] 2018-11-13 21:55
```
time (repeat 10; do; command git status --porcelain >/dev/null; done;)
( repeat 10; do; command git status --porcelain > /dev/null; done; )  0.03s user 0.04s system 58% cpu 0.114 total

time (repeat 10; do; command git ls-files --others --exclude-standard >/dev/null || command git submodule foreach --quiet --recursive 'git ls-files --others --exclude-standard' >/dev/null; d\
one;)
( repeat 10; do; command git ls-files --others --exclude-standard > /dev/null)  0.02s user 0.02s system 62% cpu 0.070 total

time (repeat 10; do; prompt_vcs left 1 false >/dev/null; done;)
( repeat 10; do; prompt_vcs left 1 false > /dev/null; done; )  0.67s user 0.78s system 71% cpu 2.034 total

time (repeat 10; do; prompt_vcs left 1 false >/dev/null; done;)
( repeat 10; do; prompt_vcs left 1 false > /dev/null; done; )  0.78s user 0.90s system 70% cpu 2.364 total
```

**Comment by ijoseph** [comment] 2018-11-13 22:00
In short, it's not a big repo. Furthermore, after switching to the `next` branch, the rendering time is livable, if not ideal.  About 0.5 seconds.

**Comment by ijoseph** [comment] 2018-11-13 22:09
I did the profiling again, this time definitely not on a version-controlled directory (`/tmp`). See the bottom of the [updated notebook](https://anaconda.org/isaac.joseph/profile/notebook). Still, `+vi-git-untracked` is the most time-consuming command, it seems like.

**Comment by dritter** [comment] 2018-11-15 00:40
Thanks for clearing that up. And no need to apology. I think these graphs are awesome. Maybe it would be possible to extend them to a more generic point. I wish we had some kind of performance testing within travis. But this seems to be [impossible](https://github.com/travis-ci/travis-ci/issues/352). 

About `vcs_comm[gitdir]` is set by [vcs_info](https://github.com/zsh-users/zsh/blob/7292c063e8fe38c9212bfb47880934effc052ae1/Functions/VCS_Info/Backends/VCS_INFO_detect_git#L10).

**Comment by romkatv** [comment] 2019-02-27 19:52
I implemented a custom binary in C (using libgit2) that prints everything relevant about the current git repo in an easy-to-parse form. It's about 40% faster than a single `git status` call and an order of magnitude faster than `vcs_info`, which makes a dozen `git` calls. I also integrated it with Powerlevel9k. If you want to try it in your current shell without any permanent changes, copy-paste the command from https://github.com/bhilburn/powerlevel9k/issues/1170#issuecomment-467977064 and see if your prompt becomes more responsive.

**Comment by gshanbhag525** [comment] 2020-01-12 08:56
There is powerlevel10k now. It's 10 times faster than powerlevel9k and backward-compatible with its configs. You can switch theme without changing any of your POWERLEVEL9K options to keep the same prompt you are used to while making it blazingly fast.

First, clone powerlevel10k.
`git clone https://github.com/romkatv/powerlevel10k.git $ZSH_CUSTOM/themes/powerlevel10k`

**Comment by gshanbhag525** [comment] 2020-01-12 08:57
> There is powerlevel10k now. It's 10 times faster than powerlevel9k and backward-compatible with its configs. You can switch theme without changing any of your POWERLEVEL9K options to keep the same prompt you are used to while making it blazingly fast.
> 
> First, clone powerlevel10k.
> `git clone https://github.com/romkatv/powerlevel10k.git $ZSH_CUSTOM/themes/powerlevel10k`

Then set ZSH_THEME=powerlevel10k/powerlevel10k in your ~/.zshrc and restart zsh.

**Comment by SimonSelg** [comment] 2020-03-07 10:24
@gshanbhag525 thank you so much for bringing this to my attention.
