### ISSUE TITLE
Request: Conditional Background Color on Custom Segment

### ISSUE THREAD

**Issue by ShakataGaNai** [bhilburn/powerlevel9k#694] opened 2017-12-06 21:10 UTC
I am attempting to utilize a custom battery segment that changes background color based on charge level/etc. It _seems_ to me that I cannot override the background color because it will not change the separator as well. Please advise if this is an actual issue or PEBKAC (there isn't much documentation on custom segments).

![image](https://user-images.githubusercontent.com/1415068/33685466-892ffe3a-da86-11e7-8184-67ae8a600140.png)

Note the white separator. That's only coincidentally the same as the text color (not related, I have tested)

Custom Segment Code:
```
zsh_battery() {
  # http://fontawesome.io/cheatsheet/
  SYM="\uf011 "
  CHG="\uf1e6 "
  BATTF="\uf240 "
  BATTH="\uf242 "
  BATTE="\uf244 "

    b=$(battery_pct)
    if plugged_in ; then
      SYM=$CHG
      BCLR=blue
    else
      if [ $b -gt 50 ] ; then
        SYM=$BATTF
        BCLR=green
      elif [ $b -gt 20 ] ; then
        SYM=$BATTH
        BCLR=yellow
      else
        SYM=$BATTE
        BCLR=red
      fi
    fi
    echo -n "%K{$BCLR%} $SYM$b%%% "
}
```

config:
```
POWERLEVEL9K_CUSTOM_BATTERY="zsh_battery"
POWERLEVEL9K_CUSTOM_BATTERY_FOREGROUND="white"
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(status os_icon dir vcs newline context )
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(time custom_internet_signal custom_battery)
```

**Comment by Artistan** [comment] 2017-12-14 14:46
I think i fixed some of this in the "new" branch. check it out.

**Comment by bhilburn** [comment] 2017-12-14 21:47
So, you should definitely be able to override that background color. We are currently working on improving some color items in `next`, right now, which is actually broken at the moment with regard to background colors. As soon as we get it fixed I'll let you know and you can give it a shot.

**Comment by ShakataGaNai** [comment] 2017-12-14 21:52
Thanks for the reply. I updated the issue title to make it clear this is a "feature request" (that is already being done per PR #684 / Bug #702 ) rather than PEBKAC.

**Comment by Artistan** [comment] 2017-12-15 21:49
I put in a pull request that fixes "next" colors.

**Comment by bhilburn** [comment] 2017-12-30 22:26
I'm going to go ahead and close this out since we are tracking the work in PR #684 and Issue #702.

**Closed by bhilburn** 2017-12-30 22:26 UTC

**Comment by Artistan** [comment] 2017-12-31 07:13
confirmed this bug in the next branch and fixed in current pull request.

**Comment by tdmalone** [comment] 2019-03-20 07:32
I'd love to do this too - set a conditional background colour on a custom segment - and it's unclear to me how to do so from the linked issues. I'm assuming this was a solved bug, but is anyone on this ticket able to assist with how to do this?

This:
```
result="EXPIRED"
state_color='%K{1}'

echo "%{$state_color%}(${result})"
```

currently results in this:
![image](https://user-images.githubusercontent.com/900469/54666630-5b1a0c00-4b3e-11e9-87d6-25fe2bbe7cee.png)

where I'd love to have the final arrow also coloured red :)
