### ISSUE TITLE
powerline9k breaks `Ctrl-C`

### ISSUE THREAD

**Issue by githorse** [bhilburn/powerlevel9k#714] opened 2018-01-02 19:07 UTC
Using this theme breaks `Ctrl-C` for me. Hitting `Ctrl-C` in the middle of certain long-running operation now just prints `$RPROMPT_PREFIX$(build_right_prompt)` to the screen; I have to hit `Ctrl-C` four or five times to actually quit. 

```
 ~/a/b/c > master > long_running_task
                                                      $RPROMPT_PREFIX$(build_right_prompt)
                                                      $RPROMPT_PREFIX$(build_right_prompt)
                                                      $RPROMPT_PREFIX$(build_right_prompt)
                                                      $RPROMPT_PREFIX$(build_right_prompt)
 ~/a/b/c > master >
```

This doesn't always happen, but happens frequently on certain commands. Other zsh themes (e.g. agnoster) don't cause this issue (with the same commands). Removing the right prompt (`POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()`) does not change the problem.

Ideas?

**Comment by bhilburn** [comment] 2018-01-30 21:54
Hey @githorse - So sorry for the delayed response, here! 

YES. I see this too, actually. You actually don't have to hit it multiple times - it worked on the first time. At least for me, you can actually type a new command and execute it, even when that prompt drawing error occurs. Regardless, it's obnoxious and interrupts the flow.

I *believe* this problem might be related to how long the `vcs` segment can take to complete. Can you try removing the `vcs` segment and giving it another go? Do you see the same issue?

**Comment by andreroggeri** [comment] 2018-02-02 16:27
@bhilburn For me, removing the vcs fixes the issue.

**Comment by bhilburn** [comment] 2018-02-02 17:58
Okay, I have a suspicion that integrating the work @quicknir did in #732 is going to improve things here. I'll update again once I've pushed / merged changes.

**Comment by bhilburn** [comment] 2018-10-08 20:41
I'm going to close this in favor of #812. Technically, that one is actually the duplicate of this one, but that one has bubbled to the top for whatever reason, hah. 

@andreroggeri @githorse - If you wouldn't mind trying the `next` branch and letting us know if you are still seeing this behavior in #812, that would be SUPER helpful.

**Closed by bhilburn** 2018-10-08 20:41 UTC
Labels: bug, master
