### ISSUE TITLE
Vi_Mode Segment not being displayed.

### ISSUE THREAD

**Issue by IQubic** [bhilburn/powerlevel9k#416] opened 2017-02-26 06:12 UTC
I'm so baffled as to why this isn't working. I'm running Gentoo Linux, with the latest version of powerlevel9k. I have run `bindkey -v`, to make sure I'm in vi mode. I have made sure that the segment is added to my status line. I'm just not seeing the segment being displayed at all. I don't have any error messages at all, I just simply flat out don't have the segment being displayed.

Here's my Powerlevel9k set up, in case that helps:

    ZSH_THEME="powerlevel9k/powerlevel9k"
    POWERLEVEL9K_MODE='awesome-fontconfig'
    POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir vi_mode vcs)
    POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(time battery)
    POWERLEVEL9K_TIME_FORMAT="%D{%H:%M:%S} \uf017"
    POWERLEVEL9K_BATTERY_ICON="\uf240"
    POWERLEVEL9K_VCS_GIT_ICON="\uf092"
    POWERLEVEL9K_SHORTEN_STRATEGY="truncate_middle"
    POWERLEVEL9K_SHORTEN_DIR_LENGTH=3

**Comment by IQubic** [comment] 2017-02-26 07:45
Just to clarify, I'm using both 'bindkey -v' and oh-my-zsh's vi-mode plugin at the same time.

**Comment by dritter** [comment] 2017-02-26 09:44
This is a duplicate of #319 . Could you have a look at my PR #344 ? This should fix your problem.

**Comment by IQubic** [comment] 2017-02-26 18:02
Since I see that this is a duplicate, I'll move the conversation over to that thread.

**Comment by dritter** [comment] 2017-03-01 17:54
Closing that issue. Duplicate of #319

**Closed by dritter** 2017-03-01 17:54 UTC
