### ISSUE TITLE
Question mark after adding to git repo

### ISSUE THREAD

**Issue by joeminicucci** [bhilburn/powerlevel9k#1239] opened 2019-04-03 18:29 UTC
ZSH Version: 5.7.1 (x86_64-apple-darwin18.2.0)
Terminal Emulator: Native Mac, ITerm2
Fonts: Nerd Fonts
OS: MacOS 10.14.4 Mojave

Everytime as soon as I add an untracked local change to my git repository, a question mark appears. I am not sure if it is trying to load a missing glyph or symbol but it is ubiquitous across all of my terminal emulators. 

![image](https://user-images.githubusercontent.com/6384324/55503533-14cbaf00-560c-11e9-8210-67085886688c.png)

**Comment by Syphdias** [comment] 2019-04-03 19:36
Literally a feature and not a bug ;)
Find the documentation on vcs here: https://github.com/bhilburn/powerlevel9k#vcs
and on vcs icons here: https://github.com/bhilburn/powerlevel9k#vcs-symbols

Remove `git-untracked` from the Array `POWERLEVEL9K_VCS_GIT_HOOKS`, e.g. by manually setting the hooks you want. You could also change the icon if you wanted.

**Comment by dritter** [comment] 2019-04-20 10:08
Closing this, as @Syphdias explains it perfectly. @joeminicucci feel free to reopen, if there is still an issue.

**Closed by dritter** 2019-04-20 10:08 UTC
