### ISSUE TITLE
Nerd-font mode is lack of some icons

### ISSUE THREAD

**Issue by AkikoZ** [bhilburn/powerlevel9k#435] opened 2017-03-13 03:09 UTC
I use nerd-font mode in Powerlevel9k. Recently I enabled the `dir_writable` segment and found that the lock icon is missing.
After inspecting the `icons.zsh` I found that the lock icon is not included in nerd-font mode, however nerd-font does have a lock icon which is `\uF023`. So I wonder that is there any reason that some icons are not included in nerd-font mode?

**Comment by bhilburn** [comment] 2017-03-14 21:34
Not being a nerd-font user myself, I can't comment on specific code points. That said, I think we have seen that code-point variation in nerdfonts can be problematic.

@kaymmm @lcorsini @akrueger - do you have the lock icon in the fonts that you are using? Should we move the code-point to `\uF023`?

**Comment by rjorgenson** [comment] 2017-03-14 21:43
Maybe we should setup a wiki page where users can add which nerdfont fonts match the codepoints we have setup and which fonts have which missing code points. This could help us narrow down a list of supported nerdfonts with their sources and a resource for users who want to use other fonts to get correct code points.

**Comment by kaymmm** [comment] 2017-03-14 21:51
It looks like the problem is that the `LOCK_ICON`, `EXECUTION_TIME_ICON`, and `SSH_ICON` aren't defined for `nerdfont-fontconfig`. The `\uF023` codepoint looks good to me.

**Comment by lcorsini** [comment] 2017-03-15 09:44
\UF023 looks good, 
As for icons undefined, when I tried to make my patch I copied all icons defined in awesome-fontconfig in icons.zsh and those wheren't defined in the version I forked

**Comment by lcorsini** [comment] 2017-03-15 13:44
I noticed also that there is some icons missing using the latest next branch on my linux pc at work
This is p9k next branch
![p9knext](https://cloud.githubusercontent.com/assets/1501930/23950859/afe7b4bc-098c-11e7-9605-96e9d00e4470.JPG)
This is my patch
![p9klcorsini](https://cloud.githubusercontent.com/assets/1501930/23950882/bd085d36-098c-11e7-9a14-48fc377b6771.JPG)

apart from the amazon icons I miss node, todo and BSD icons. are there any changes that I'm not aware?
I've used latest SauceCodePro as my font

this is a diff of the two icons.zsh
[diff.txt](https://github.com/bhilburn/powerlevel9k/files/844654/diff.txt)

**Comment by bhilburn** [comment] 2017-03-16 00:55
@lcorsini - Can you file a PR to replace the missing icons for the nerdfont option?

**Comment by lcorsini** [comment] 2017-03-16 06:46
@bhilburn Ok done

**Comment by bhilburn** [comment] 2017-03-21 02:21
Fixed by merge of #451!

**Closed by bhilburn** 2017-03-21 02:21 UTC
Labels: Fonts, next, question
