### ISSUE TITLE
Very slow in home folder because of VCS prompt segment

### ISSUE THREAD

**Issue by dj-hedgehog** [bhilburn/powerlevel9k#244] opened 2016-04-08 15:58 UTC
I turned my home-folder `~` into a dotfiles repository with a lot of untracked files.
Ever since I made this change zsh is unusable slow while I'm located in the home-folder. It takes like 5-10 seconds to register keystrokes or execute anything.

Since I like the VCS segment I'd like to know what I can do about it without removing it entirely? Can I disable it in certain folders or is there some git function I can use?

**Comment by jguenther** [comment] 2016-04-08 18:40
What I do is I make a `~/dotfiles` repo and have a makefile in there that symlinks `~/.file` to `~/dotfiles/file`  if they don't already exist. e.g. `~/.bashrc` is a symlink to `~/dotfiles/bashrc`, etc.

**Comment by dritter** [comment] 2016-04-08 20:56
@dj-hedgehog Thanks for the report.

The way @jguenther suggests would work. But I don't like it that this theme slows your terminal that much down. So I create a repository with 500.000 untracked files, and voilá it is slow as hell.
For now I can say that it has to do with the checking of untracked files. If I deactivate this (currently only available on the `next` branch) by setting `POWERLEVEL9K_VCS_GIT_HOOKS=(vcs-detect-changes git-aheadbehind git-stash git-remotebranch git-tagname)` (notice that I took out `git-untracked`). This is no real solution, as it deactivates the whole checking of untracked files for all repositories.
I need to investigate this further. Just wanted to inform you about my ongoings.

**Comment by dritter** [comment] 2016-04-09 15:08
Bad news: This is an issue of git itself. My first thought was, to cut off the response of git (with `tail -n 1`), but git computes the whole list of files before handing over to tail.. Second thought was to add an `.gitignore` with all untracked files in it (or a `*`), but git needs to check each file against this mask (which is slow). There seems no way to get just a boolean value out of git to know if there is an untracked file at all.
Even other commands than `git status` are not fast enough (like `git ls-files`, as suggested [here](http://stackoverflow.com/questions/11021287/git-detect-if-there-are-untracked-files-quickly)).

IMHO there are two ways that would work:

1. as @jguenther suggested, clone your dotfiles repository to another location, and link all relevant files to your home directory.

2. disable the untracked files checking in your home directory. To do so, you could add piece of code in your `.zshrc`:
```zsh
if [[ $(print -P "%~") == '~' ]]; then
  POWERLEVEL9K_VCS_GIT_HOOKS=(vcs-detect-changes git-aheadbehind git-stash git-remotebranch git-tagname)
fi
```

But apart from that, all we could do is sending a patch to git..
Sorry.

**Comment by bhilburn** [comment] 2016-04-11 19:18
@dritter - What are your thoughts on moving the dirty check into a `precmd`? It seems like that might speed up the responsiveness of the re-draw, if I'm understanding how it works correctly?

**Comment by dritter** [comment] 2016-04-12 18:42
Hmm. The only way how I imagine these precmds are executed are:

1. right before the prompt is printed. Then it will make no difference to executing this function as vcs_info-hook

2. less often. This would make a difference, but will give us not enough information (the underlying repo might have changed in the meantime).

I think there is no faster way than doing it like we do (except for the async way). Best would be submitting a PR to git, adding a new command that will stop right after a valid (considering the `.gitignore`) untracked file was found.

**Comment by bhilburn** [comment] 2016-04-12 21:17
@dritter - Thanks for the thoughts!

Hm... maybe I'll look into what it would take to do that check asynchronously, as the project  did in your link. That would be pretty cool, but it sounds like the workload might be... heavy.

**Comment by chenjuntong** [comment] 2016-04-30 17:24
Same problem.Waiting for the solution.

**Comment by chenjuntong** [comment] 2016-05-01 19:46
@dritter 
On my computer it seems that both "symlinks" and "modify.zshrc" ways don't work at all.

**Comment by dritter** [comment] 2016-05-02 16:07
@chenjuntong This is strange. Do you have a huge repository as well? Or does this happen in any repository (even small ones)?
And do you operate on a network-mounted folder?

**Comment by chenjuntong** [comment] 2016-05-04 07:41
@dritter This happen in any repository.When using powerlevel9k, the entire zsh seems slow down. Even simple command like "cd" is slower too. Extremely slow when using vcs. Therefore whether I operate on local folders(which I operate on) or network-mounted folders it is the same.

**Comment by dritter** [comment] 2016-05-04 08:55
@chenjuntong That is strange. The `vcs` segment uses ZSHs `VCS_INFO` which does massively disk operations. So the `vcs` segment should be significantly faster on local folders than on network mounts..

Are your repositories git or mercurial ones? (Git should be faster than mercurial).

And how fast is the invocation of `time git status` or `time hg st` in your repo (with disabled vcs of course)? If the pure command is slow, this is something we cannot do anything about..

**Comment by chenjuntong** [comment] 2016-05-05 01:18
@dritter My repositories are git ones.
Here is the time git status.Seems fast.
![](http://ww2.sinaimg.cn/large/6ccda21fjw1f3k8ocj43aj20j80bvtao.jpg)
When I disable vcs，every command becomes fast as usual.Therefore I guess the problem is on vcs.
Thanks for your patience.

**Comment by bhilburn** [comment] 2016-05-14 16:10
Yeah, there seem to be some speed issues with ZSH's `VCS_INFO` submodule. As @dritter said before, the only way we might be able to get around this is to force some things to run asynchronously to the prompt draw. I haven't had a chance to look into this, yet, but would like to.

If anyone else is interested in contributing on this front, I consider this to be an important effort.

**Comment by andjscott** [comment] 2016-05-15 14:46
I've made the RPROMPT async based on [this blog post](http://www.anishathalye.com/2015/02/07/an-asynchronous-shell-prompt/). Currently the whole RPROMPT is generated as one unit but it would be nice to split up the elements so they arrive as soon as they are loaded. E.g.

    echo -n $(time_message) >> $socket
    kill -s USR1 $$
    echo -n $(vcs_message) >> $socket
    kill -s USR1 $$

My commit is at https://github.com/andjscott/powerlevel9k/commit/780a31e95d4dd930a74a726638a0d9f1eab616e0 if you are interested.

**Comment by chenjuntong** [comment] 2016-05-16 12:47
@andjscott  The solution works! Thanks very much!

**Comment by chenjuntong** [comment] 2016-05-16 13:06
@andjscott I am sorry that this solution hasn't completely solve the problem. It maybe a little faster than the original config. Still, every command slower when using the VCS_INFO.

**Comment by andjscott** [comment] 2016-05-18 01:57
`powerlevel9k_prepare_prompts` gets called twice currently due to the `zle-line-init` and the `precmd` hooks. Is there a reason for this? The prompt seems to work fine without the `zle-line-init` hook.

**Comment by dritter** [comment] 2016-05-18 07:57
@andjscott Only accidental. :D We had some trouble getting the `vi_mode` to work. The bug was introduced at this time..

Btw. the async prompt looks awesome! Thank you very much!

**Comment by bhilburn** [comment] 2016-05-27 16:09
Work continues in #263...

**Comment by andela-oadesanya** [comment] 2016-05-29 00:42
@chenjuntong try `brew install git`
Had the same issue, my terminal was extremely slow after installing the powerlevel9k theme, and spent hours trying to get it solved until I hit `brew install git` to override the default git that was shipped with my OSX.
`brew install git` worked just fine for me.

**Comment by bhilburn** [comment] 2016-06-14 02:37
@andela-oadesanya - Wow, really? Do you know what version ships with OSX by default, and what version of git you have now?

**Comment by dritter** [comment] 2016-06-14 22:18
@bhilburn Apple ships `git version 2.7.4 (Apple Git-66)` on El Capitan (10.11.5).

**Comment by bhilburn** [comment] 2016-08-11 19:52
Closing this to continue async work in #263 and vcs speedup work in #287.

**Comment by chenjuntong** [comment] 2016-08-18 08:15
@andjscott @andela-oadesanya @bhilburn  "removing-zle-functions: https://github.com/bhilburn/powerlevel9k/tree/removing-zle-funcs" has solved this problem. Thank you!

**Comment by bhilburn** [comment] 2016-08-18 12:48
@chenjuntong - Happy to hear that! We'll get that merged into master soon.

**Closed by bhilburn** 2016-08-18 12:48 UTC
