### ISSUE TITLE
vi_mode indicator doesn't seem to work

### ISSUE THREAD

**Issue by kramachandran** [bhilburn/powerlevel9k#328] opened 2016-10-23 20:17 UTC
The vi_mode indicator doesn't seem to work when used in conjunction with oh-my-zsh vi-mode plugin. 

For some reason the KEYMAP variable doesn't appear to be available to powerlevel.

**Comment by bhilburn** [comment] 2016-10-26 13:37
Thanks for the bug report, @kramachandran! Closing as a duplicate of #319.

**Closed by bhilburn** 2016-10-26 13:37 UTC
Labels: bug, duplicate
